apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y9l4rnmis-nodejs
  janus-idp.io/tekton: y9l4rnmis-nodejs
  backstage.io/kubernetes-id: y9l4rnmis-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y9l4rnmis-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
